name: firebase_authentication_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# homepage: https://www.example.com
environment:
  sdk: ">=2.14.3 <3.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  google_sign_in: ^5.1.1
